/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package randomcolor;

import java.awt.*;
import java.awt.datatransfer.*;
import java.util.Random;
import javax.swing.event.ChangeListener;

/**
 *
 * @author perlengkapan
 */
public class RandomColor extends javax.swing.JFrame {

    /**
     * Creates new form RandomColor1
     */
    public RandomColor() {
        initComponents();
    }
    
    public void generateColor(){
        Random random = new Random();
        int r, g, b;
        r = random.nextInt(255);
        g = random.nextInt(255);
        b = random.nextInt(255);
        
        Color color = new Color(r, g, b);
        String hex = Integer.toHexString(color.getRGB() & 0xffffff);
        hex = "#" + hex;
        
        hex_color.setText(hex);
        color_R.setText(String.valueOf(r)+",");
        color_G.setText(String.valueOf(g)+",");
        color_B.setText(String.valueOf(b));
        
        panel_color.setBackground(color);
        panel_2.setBackground(color);
        
        sliderR.setValue(r);
        sliderG.setValue(g);
        sliderB.setValue(b);
    }
    
    public void copyClipboard(String warna){        
        String copyWarna = warna;
        StringSelection stringSelection = new StringSelection(copyWarna);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }
    
    public void sliderChange(){
        int valueR = sliderR.getValue();
        int valueG = sliderG.getValue();
        int valueB = sliderB.getValue();
        
        Color color = new Color(valueR, valueG, valueB);
        panel_color.setBackground(color);
        panel_2.setBackground(color); 
        
        Color colorState = new Color(valueR, valueG, valueB);
        String hex = Integer.toHexString(colorState.getRGB() & 0xffffff);
        hex = "#" + hex;
        hex_color.setText(hex);
        
        color_R.setText(String.valueOf(valueR)+",");
        color_G.setText(String.valueOf(valueG)+",");
        color_B.setText(String.valueOf(valueB));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_color = new javax.swing.JPanel();
        hex_color = new javax.swing.JLabel();
        btn_generate = new javax.swing.JButton();
        sliderR = new javax.swing.JSlider();
        sliderG = new javax.swing.JSlider();
        sliderB = new javax.swing.JSlider();
        kurung2 = new javax.swing.JLabel();
        kurung1 = new javax.swing.JLabel();
        panel_2 = new javax.swing.JPanel();
        color_R = new javax.swing.JLabel();
        color_G = new javax.swing.JLabel();
        color_B = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random Color Generator");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        panel_color.setBackground(new java.awt.Color(0, 0, 0));
        panel_color.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hex_color.setFont(new java.awt.Font("Loew Medium", 0, 24)); // NOI18N
        hex_color.setForeground(new java.awt.Color(255, 255, 255));
        hex_color.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hex_color.setText("#000000");
        hex_color.setToolTipText("Copy Hex Color");
        hex_color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hex_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hex_colorMouseClicked(evt);
            }
        });
        panel_color.add(hex_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 440, 30));

        btn_generate.setBackground(new java.awt.Color(255, 255, 255));
        btn_generate.setFont(new java.awt.Font("Loew Medium", 0, 13)); // NOI18N
        btn_generate.setForeground(new java.awt.Color(0, 0, 0));
        btn_generate.setText("Generate Random");
        btn_generate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        btn_generate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });
        panel_color.add(btn_generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 160, -1));

        sliderR.setMaximum(255);
        sliderR.setValue(0);
        sliderR.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRStateChanged(evt);
            }
        });
        panel_color.add(sliderR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        sliderG.setMaximum(255);
        sliderG.setValue(0);
        sliderG.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGStateChanged(evt);
            }
        });
        panel_color.add(sliderG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        sliderB.setMaximum(255);
        sliderB.setValue(0);
        sliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBStateChanged(evt);
            }
        });
        panel_color.add(sliderB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        kurung2.setFont(new java.awt.Font("Loew Medium", 0, 12)); // NOI18N
        kurung2.setForeground(new java.awt.Color(255, 255, 255));
        kurung2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kurung2.setText(")");
        kurung2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_color.add(kurung2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 152, 20, -1));

        kurung1.setFont(new java.awt.Font("Loew Medium", 0, 12)); // NOI18N
        kurung1.setForeground(new java.awt.Color(255, 255, 255));
        kurung1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kurung1.setText("( ");
        kurung1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_color.add(kurung1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 152, 20, -1));

        panel_2.setBackground(new java.awt.Color(0, 0, 0));
        panel_2.setToolTipText("Copy RGB");
        panel_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_2MouseClicked(evt);
            }
        });
        panel_2.setLayout(null);

        color_R.setFont(new java.awt.Font("Loew Medium", 0, 12)); // NOI18N
        color_R.setForeground(new java.awt.Color(255, 255, 255));
        color_R.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        color_R.setText("0,");
        color_R.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_2.add(color_R);
        color_R.setBounds(10, 2, 30, 18);

        color_G.setFont(new java.awt.Font("Loew Medium", 0, 12)); // NOI18N
        color_G.setForeground(new java.awt.Color(255, 255, 255));
        color_G.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        color_G.setText("0,");
        color_G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_2.add(color_G);
        color_G.setBounds(40, 2, 30, 18);

        color_B.setFont(new java.awt.Font("Loew Medium", 0, 12)); // NOI18N
        color_B.setForeground(new java.awt.Color(255, 255, 255));
        color_B.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        color_B.setText("0");
        color_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_2.add(color_B);
        color_B.setBounds(70, 2, 30, 18);

        panel_color.add(panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("R");
        panel_color.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 260, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("G");
        panel_color.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 280, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("B");
        panel_color.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_color, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed
        // TODO add your handling code here:
        generateColor();
    }//GEN-LAST:event_btn_generateActionPerformed

    private void hex_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hex_colorMouseClicked
        // TODO add your handling code here:
        copyClipboard(hex_color.getText());
    }//GEN-LAST:event_hex_colorMouseClicked

    private void sliderRStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRStateChanged
        // TODO add your handling code here:
        sliderChange();
    }//GEN-LAST:event_sliderRStateChanged

    private void sliderGStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGStateChanged
        // TODO add your handling code here:
        sliderChange();
    }//GEN-LAST:event_sliderGStateChanged

    private void sliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBStateChanged
        // TODO add your handling code here:
        sliderChange();
    }//GEN-LAST:event_sliderBStateChanged

    private void panel_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_2MouseClicked
        // TODO add your handling code here:
        String r = color_R.getText();
        String g = color_G.getText();
        String b = color_B.getText();
        String rgb = r+g+b;
        copyClipboard(rgb);
    }//GEN-LAST:event_panel_2MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RandomColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RandomColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RandomColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RandomColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RandomColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generate;
    private javax.swing.JLabel color_B;
    private javax.swing.JLabel color_G;
    private javax.swing.JLabel color_R;
    private javax.swing.JLabel hex_color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel kurung1;
    private javax.swing.JLabel kurung2;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_color;
    private javax.swing.JSlider sliderB;
    private javax.swing.JSlider sliderG;
    private javax.swing.JSlider sliderR;
    // End of variables declaration//GEN-END:variables
}
